### ISSUE TITLE
fatal: Unsupported command: <mercurial.httprepo.httprepository object at 0x1012f6290>

### ISSUE THREAD

**Issue by selkhateeb** [vitaly/hg2git#1]
Any ideas whats causing the problem? I am useing a Mac Snow Leopard, Python 2.6 and the latest Hg lib (downloaded using easy_install)

Here is the traceback I m getting

Traceback (most recent call last):
fatal: Unsupported command: <mercurial.httprepo.httprepository object at 0x1012f6290>
  File "./hg2git.py", line 451, in <module>
    options.statusfile,authors=a,sob=options.sob,force=options.force))
  File "./hg2git.py", line 386, in hg2git
    if not verify_heads(ui,repo,heads_cache,force):
  File "./hg2git.py", line 348, in verify_heads
    branches=repo.branchtags()
AttributeError: 'httprepository' object has no attribute 'branchtags'
fast-import: dumping crash report to .git/fast_import_crash_50331
Git fast-import failed

Thanks in advance

**Comment by vitaly** [comment]
sorry, but I'm not a maintainer of this and don't really know the internals. as the repository description says this is just a point-in-time-snapshot from http://git.utsl.gen.nz/mirror/repo.or.cz/hg2git.git

Note that I also don't use it anymore as there are better tools now.
I recommend you try out this: http://hg-git.github.com/
